services:
  client:
    image: bluewaveuptime/uptime_client:latest
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "http://${DOMAIN}/api/v1"
    depends_on:
      - server
    networks:
      - dbNet
      - dokploy-network

  server:
    image: bluewaveuptime/uptime_server:latest
    restart: always
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://checkmate-mongodb:27017/uptime_db
      - REDIS_HOST=checkmate-redis
      - SYSTEM_EMAIL_HOST=${EMAIL_HOST}
      - SYSTEM_EMAIL_PORT=${EMAIL_PORT}
      - SYSTEM_EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - SYSTEM_EMAIL_PASSWORD=${EMAIL_PASSWORD}
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dbNet

  redis:
    image: bluewaveuptime/uptime_redis:latest
    restart: always
    hostname: checkmate-redis
    volumes:
      - ../files/redis/data:/data
    networks:
      - dbNet
  
  mongodb:
    image: bluewaveuptime/uptime_database_mongo:latest
    restart: always
    hostname: checkmate-mongodb
    volumes:
      - ../files/mongo/data:/data/db
    command: ["mongod", "--quiet"]
    networks:
      - dbNet

networks:
  dokploy-network:
  dbNet: