[variables]
main_domain = "${domain}"  
my_password = "${password:32}" 
any_helper = "${uuid}"  

[config]

[[config.domains]]
serviceName = "dragonflydb"
port = 6379
host = "${main_domain}"  
path = "/"

env = [
    "DFDB_PASSWORD=${my_password}",
    "DFDB_HOST=${main_domain}", 
    "DFDB_CLUSTER_ENABLED=${randomPort}",
    "DFDB_LOG_LEVEL=info"
]

[[config.mounts]]
filePath = "/content/configuration.conf"
content = """
bind-address = "0.0.0.0"
port = 6379
log-level = "info"
"""
