[variables]
main_domain = "${domain}"

[config]
env = [
"Domain=${main_domain}",
"POSTGRES_USER=plane",
"POSTGRES_PASSWORD=plane",
"POSTGRES_DB=plane",
"RABBITMQ_VHOST=plane",
"RABBITMQ_HOST=plane-mq",
"RABBITMQ_PORT=5672",
"RABBITMQ_USER=plane",
"RABBITMQ_PASSWORD=plane",
"RABBITMQ_DEFAULT_USER=plane",
"RABBITMQ_DEFAULT_PASS=plane",
"RABBITMQ_DEFAULT_VHOST=plane",
"MINIO_ROOT_USER=minioaccesskey",
"MINIO_ROOT_PASSWORD=miniorootpassword",
"REDIS_HOST=plane-redis",
"REDIS_PORT=6379",
"AWS_S3_ENDPOINT_URL=http://plane-minio:9000",
"AWS_S3_BUCKET_NAME=uploads",
"FILE_SIZE_LIMIT=5242880",
"USE_MINIO=1",
"MINIO_ENDPOINT_SSL=0",
"API_KEY_RATE_LIMIT=60/minute",
"TZ=UTC",
]
mounts = []

[[config.domains]]
serviceName = "plane"
port = 8065
host = "${main_domain}"
